apiVersion: v1
kind: Secret
metadata:
  name: {{ include "behavior-auth.fullname" . }}-secret
  labels:
    {{- include "behavior-auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: "{{ .Values.secrets.jwtSecret }}"
  MFA_KEY: "{{ .Values.secrets.mfaKey }}"
  DATABASE_URL: "{{ .Values.secrets.databaseUrl }}"
  REDIS_URL: "{{ .Values.secrets.redisUrl }}"
